//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGit.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectGit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1	17	1	0	0	0
        ///2	22	1	0	0	0
        ///3	23	1	0	0	1
        ///4	25	1	0	0	0
        ///5	26	1	0	0	0
        ///6	27	1	1	0	0
        ///7	28	1	0	0	0
        ///9	30	1	0	0	1
        ///10	30	1	0	0	0
        ///11	30	1	1	0	0
        ///12	32	1	0	0	0
        ///13	32	1	0	0	1
        ///14	32	1	0	0	1
        ///15	32	1	1	0	0
        ///16	32	1	1	0	0
        ///17	32	1	1	1	0
        ///18	33	1	0	0	1
        ///19	33	1	0	0	0
        ///20	33	1	0	0	1
        ///21	33	1	1	0	1
        ///22	33	0	1	0	1
        ///23	33	1	1	0	0
        ///24	33	1	1	0	1
        ///25	33	1	1	0	0
        ///27	34	1	0	0	0
        ///28	34	1	0	0	1
        ///29	34	1	0	0	0
        ///30	34	1	0	0	1
        ///31	34	1	0	0	0
        ///32	34	1	0	0	1
        ///33	34	1	1	0	0
        ///34	34	1	1	0	0
        ///35	34	1	1	0	0
        ///36	34	1	1	1	1
        ///37	35	1	0	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TrainSelection {
            get {
                return ResourceManager.GetString("TrainSelection", resourceCulture);
            }
        }
    }
}
